# Generated by Django 3.1.1 on 2020-09-17 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('age', models.IntegerField(default='nieznany')),
                ('image', models.ImageField(upload_to='')),
                ('about', models.TextField(default='brak informacji')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='')),
                ('about', models.TextField(blank=True)),
                ('author', models.ForeignKey(default='nieznany', on_delete=django.db.models.deletion.SET_DEFAULT, to='books.author')),
            ],
        ),
    ]
